<a href="https://colab.research.google.com/github/choki0715/lecture/blob/master/autograd_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [8]:
pred = 3*a**3 - b**2

In [9]:
label = torch.tensor([2.])

In [10]:
cost = (pred - label)**2

In [11]:
cost.backward()

In [12]:
a.grad

tensor([-972.])

In [13]:
b.grad

tensor([324.])

In [7]:
9*a**2

tensor([36.], grad_fn=<MulBackward0>)