<a href="https://colab.research.google.com/github/choki0715/lecture/blob/master/numpy_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 넘파이 불러오기 및 넘파이 기본


In [1]:
import numpy as np

# ndarray basic
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


# 넘파이 기본자료구조: ndarray

In [ ]:
# ndarray 설정

a = np.zeros((2,2))   # 모든 요소가 0인 array 만들기
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # 모든 요소가 1인 array 만들기
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # 모든 요소가 정의된 숫자로 채워진 array 만들기
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         #  2x2 단위 행렬 만들기
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # 임의의 숫자가 채워진 array 만들기
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

f = np.empty((3,3)) # garbage 숫자가 채워진 array 만들기
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.81562443 0.5325044 ]
 [0.83952282 0.97618825]]
[[4.68937941e-310 4.68937940e-310 4.68937940e-310]
 [4.68937940e-310 4.68937940e-310 4.68937940e-310]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


# 인덱싱: 주어진 array에 원하는 요소를 참조하고 대체하기

In [6]:
# indexing

a = np.array([[1,2], [3, 4], [5, 6]])

# 순서에 따른 내장된 규칙에 따라 인덱싱 (고급)
aa = a[[0, 1, 2], [0, 1, 0]]
print(aa)  # Prints "[1 4 5]"
print(aa.shape)


[1 4 5]
(3,)


In [5]:

# 위 인덱싱을 직관적으로 표현
aaa = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(aaa)  # Prints "[1 4 5]"
print(aaa.shape)


[1 4 5]
(3,)


In [10]:
# Broadcasting

import numpy as np

# 벡터 v 를 차원이 같은 행렬의 행 또는 열에 더해줄 수 있음

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # 브로드캐스팅 기능을 이용하여 벡터 v를 x의 각 행에 더해줌
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
vv = np.array([[1], [1], [1], [1]])

yy = x + vv
print(yy)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


# 행렬 요소간 사칙연산: +, -, x, /
# 행렬 x 벡터, 행렬 x 행렬 연산: matmul

In [ ]:
# Math
mat1 = np.ones((3,3))
print(mat1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
cnt = 1
mat2 = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    mat2[i,j] = mat1[i,j]*cnt
    cnt = cnt + 1
print(mat2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
mat3 = (mat1 + mat2) * mat2 - mat1/mat2
print(mat3)

mat3_1 = np.subtract( np.multiply( np.add(mat1, mat2), mat2), np.divide(mat1,mat2) )
print(mat3_1)

[[ 1.          5.5        11.66666667]
 [19.75       29.8        41.83333333]
 [55.85714286 71.875      89.88888889]]
[[ 1.          5.5        11.66666667]
 [19.75       29.8        41.83333333]
 [55.85714286 71.875      89.88888889]]


In [ ]:
mat4 = np.dot(mat2, mat3)
print(mat4)

[[ 208.07142857  280.725       365.        ]
 [ 437.89285714  602.25        795.16666667]
 [ 667.71428571  923.775      1225.33333333]]


In [ ]:
mat5 = np.matmul(mat2, mat3)
print(mat5)

[[ 208.07142857  280.725       365.        ]
 [ 437.89285714  602.25        795.16666667]
 [ 667.71428571  923.775      1225.33333333]]


In [ ]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [ ]:
mat6 = np.dot(mat2, vec)
print(mat6)

[14. 32. 50.]


In [ ]:
mat7 = np.matmul(mat2, vec)
print(mat7)

[14. 32. 50.]
