<a href="https://colab.research.google.com/github/choki0715/lecture/blob/master/tennis_test_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# 테니스 날씨 데이터 만들기 

data_dict = {
    'Outlook' : ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny','Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
    ,'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild','Mild','Mild', 'Hot', 'Mild']
    ,'Humidity' : ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High','Normal','Normal', 'Normal', 'High', 'Normal', 'High']
    ,'Wind': ['False', 'True', 'False', 'False', 'False', 'True', 'True', 'False', 'False', 'False', 'True', 'True', 'False', 'True']
    ,'PlayTennis': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']
}

tennis = pd.DataFrame(data_dict, columns=data_dict.keys())
tennis

Outlook Temperature Humidity   Wind PlayTennis
0      Sunny         Hot     High  False         No
1      Sunny         Hot     High   True         No
2   Overcast         Hot     High  False        Yes
3      Rainy        Mild     High  False        Yes
4      Rainy        Cool   Normal  False        Yes
5      Rainy        Cool   Normal   True         No
6   Overcast        Cool   Normal   True        Yes
7      Sunny        Mild     High  False         No
8      Sunny        Cool   Normal  False        Yes
9      Rainy        Mild   Normal  False        Yes
10     Sunny        Mild   Normal   True        Yes
11  Overcast        Mild     High   True        Yes
12  Overcast         Hot   Normal  False        Yes
13     Rainy        Mild     High   True         No

In [2]:
# 원시 데이터 --> 학습 데이터 

x = tennis.iloc[:, range(4)]
x = pd.get_dummies(x)
y = tennis[['PlayTennis']]
y = pd.get_dummies(y)
x.head()
X = x.values
class_list = ['play NO', 'play_YES']
print(X,y) 

[[0 0 1 0 1 0 1 0 1 0]
 [0 0 1 0 1 0 1 0 0 1]
 [1 0 0 0 1 0 1 0 1 0]
 [0 1 0 0 0 1 1 0 1 0]
 [0 1 0 1 0 0 0 1 1 0]
 [0 1 0 1 0 0 0 1 0 1]
 [1 0 0 1 0 0 0 1 0 1]
 [0 0 1 0 0 1 1 0 1 0]
 [0 0 1 1 0 0 0 1 1 0]
 [0 1 0 0 0 1 0 1 1 0]
 [0 0 1 0 0 1 0 1 0 1]
 [1 0 0 0 0 1 1 0 0 1]
 [1 0 0 0 1 0 0 1 1 0]
 [0 1 0 0 0 1 1 0 0 1]]     PlayTennis_No  PlayTennis_Yes
0               1               0
1               1               0
2               0               1
3               0               1
4               0               1
5               1               0
6               0               1
7               1               0
8               0               1
9               0               1
10              0               1
11              0               1
12              0               1
13              1               0


In [3]:

import tensorflow as tf
from tensorflow import keras

# MLP 모델 설계하기

model = keras.Sequential([  
  keras.layers.Dense(10, activation='relu'),
  keras.layers.Dense(5, activation='relu'),                     
  keras.layers.Dense(2, activation='softmax')
])

# 모델 프로파일
#model.summary()

# 학습 기준 확정
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
 

In [6]:
# 학습 반복회수 설정
epochs = 250
num_batch = 14

# 학습 모델 학습
model.fit(x, y, epochs=epochs, batch_size=num_batch)

Epoch 1/250
1/1 [==============================] - 0s 29ms/step - loss: 0.5036 - accuracy: 0.8571
Epoch 2/250
1/1 [==============================] - 0s 17ms/step - loss: 0.5019 - accuracy: 0.8571
Epoch 3/250
1/1 [==============================] - 0s 23ms/step - loss: 0.5003 - accuracy: 0.8571
Epoch 4/250
1/1 [==============================] - 0s 7ms/step - loss: 0.4987 - accuracy: 0.8571
Epoch 5/250
1/1 [==============================] - 0s 8ms/step - loss: 0.4971 - accuracy: 0.8571
Epoch 6/250
1/1 [==============================] - 0s 10ms/step - loss: 0.4955 - accuracy: 0.8571
Epoch 7/250
1/1 [==============================] - 0s 16ms/step - loss: 0.4939 - accuracy: 0.8571
Epoch 8/250
1/1 [==============================] - 0s 10ms/step - loss: 0.4923 - accuracy: 0.8571
Epoch 9/250
1/1 [==============================] - 0s 8ms/step - loss: 0.4907 - accuracy: 0.8571
Epoch 10/250
1/1 [==============================] - 0s 18ms/step - loss: 0.4891 - accuracy: 0.8571
Epoch 11/250
1/1 [====

In [7]:
# sample data
x1 = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int)
x1 = x1.reshape(1,-1)
pred = model.predict(x1)
idx = np.argmax(pred)
print(class_list[idx])

play NO
